### ISSUE TITLE
ps color script

### ISSUE THREAD

**Issue by tapochek666** [scottmckendry/ps-color-scripts#1]
Hello. How to create your own ps color script?

**Comment by scottmckendry** [comment]
Can you clarify what you wanting to do? Are you wanting to generate one from an image or something?

**Comment by tapochek666** [comment]
Yes, I wanted to make my own picture and (or) my own text.

**Comment by tapochek666** [comment]
So what's with my question?

**Comment by scottmckendry** [comment]
There's tools out there that can convert images to shell scripts. One example:

https://github.com/dom111/image-to-ansi

If you want to use this in PowerShell, you'll need to replace all the bash escapes with the PowerShell equivalent. E.g. `\e` becomes `` `e``

If you want to create your own from scratch, this repo is full of examples.Let me know if you have any questions 🙂
